### ISSUE TITLE
Plugin update and Compatibility check

### ISSUE THREAD

**Issue by dhawalepranav** [rtCamp/embed-google-drive#18]
We need to complete the following set of tasks for [Embed Google Drive plugin](https://wordpress.org/plugins/embed-google-drive/).

- [x] Make sure it's compatible with latest WordPress version. (e.g 6.6.X )
- [x] Make sure it's PHP 8.2 compatible.
- [x] Make sure it's VIP compatible
- [x] Run the PHPCS scan
- [x] Document the user manual with screenshots that will include things like "How to install plugin", "Plugin Pre-requisites" "How to setup plugin for first time", "Plugin Settings with their use case" etc

Before starting the work please add your time estimations for every mentioned task and get it approved by your Project Co-ordinator or Project Manager

**Comment by SH4LIN** [comment]
## Task estimation: `7-9hrs`

### Tasks breakdown
- Check the compatibility with the latest WordPress version `1-2hr`
- Check the code is compatible with the PHP 8.2 `1-2hr`
- Make sure it's VIP compatible `45mins`
- Fix the PHPCS issues `15mins`
- Generated the documentation with the screenshots and user manual `2-3hr`
- QA of the plugin `1hr`

CC: @dhawalepranav @joelabreo227

**Comment by SH4LIN** [comment]
The plugin also needs its text domain to be updated as mentioned in [here](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains) 

> If your plugin is hosted on wordpress.org it must be the slug portion of your plugin URL (wordpress.org/plugins/<slug>)

Plugin's WordPress org slug is this https://wordpress.org/plugins/embed-google-drive -> (embed-google-drive) and current text domain is `rt-google-embeds` it needs to be refactored from `rt-google-embeds` to `embed-google-drive`.

This change will have a time estimation of `1hr`

- Need to change the file names, and text domain, Generate POT file with new text domain.

@dhawalepranav

**Comment by SH4LIN** [comment]
## Installation

1. Download the plugin from [here](https://wordpress.org/plugins/embed-google-drive/)
   <img src="https://github-production-user-asset-6210df.s3.amazonaws.com/56588503/290548823-0a2faf19-c9c4-4ea9-bed0-52f28fd66e3a.png" />
2. Add the plugin from the WordPress admin panel.
   <img src="https://github-production-user-asset-6210df.s3.amazonaws.com/56588503/290547568-462f110a-7bf0-4b2d-84fb-5e1d92226bdb.png" />
   <img src="https://github-production-user-asset-6210df.s3.amazonaws.com/56588503/290549849-4742d951-b798-4d0d-b1ef-edfd5e13dbc5.png" />
   <img src="https://github-production-user-asset-6210df.s3.amazonaws.com/56588503/290550134-147a5435-5458-4abf-bf74-4c6990da2da3.png" />
3. Activate the plugin through the 'Plugins' menu in WordPress
   <img src="https://github-production-user-asset-6210df.s3.amazonaws.com/56588503/290550390-6ee9cac6-0b57-460d-bd53-68c4cf376f68.png" />
4. Paste a shared Google Drive document link into the WordPress editor.

@dhawalepranav I am documenting these steps for the Installation of plugin and how to use it.

**Comment by SH4LIN** [comment]
Task update: PHP 8.2 compatibility sweep completed. No issues were found

WordPress 6.4.2 compatibility sweep completed. No issues were found.

PHPCS with WordPress and WordPress-VIP-Go standard fixed.

Documented how to install and use the plugin.

@dhawalepranav

**Comment by SH4LIN** [comment]
@dhawalepranav Updated README.md

## Installation

1. Download the plugin from [here](https://wordpress.org/plugins/embed-google-drive/)
   <img src="https://github-production-user-asset-6210df.s3.amazonaws.com/56588503/290548823-0a2faf19-c9c4-4ea9-bed0-52f28fd66e3a.png" />
2. Add the plugin from the WordPress admin panel.
   <img src="https://github-production-user-asset-6210df.s3.amazonaws.com/56588503/290547568-462f110a-7bf0-4b2d-84fb-5e1d92226bdb.png" />
   <img src="https://github-production-user-asset-6210df.s3.amazonaws.com/56588503/290549849-4742d951-b798-4d0d-b1ef-edfd5e13dbc5.png" />
   <img src="https://github-production-user-asset-6210df.s3.amazonaws.com/56588503/290550134-147a5435-5458-4abf-bf74-4c6990da2da3.png" />
3. Activate the plugin through the 'Plugins' menu in WordPress
   <img src="https://github-production-user-asset-6210df.s3.amazonaws.com/56588503/290550390-6ee9cac6-0b57-460d-bd53-68c4cf376f68.png" />

## How to use
1. Copy the URL of drive document which you want to embed. <b>Note: The document must be shared with anyone with the link.</b>
2. Create new post/page or edit existing one.
3. Paste the URL in the editor. It will automatically embed the document.
   ![image](https://github.com/rtCamp/embed-google-drive/assets/56588503/546fbdcd-36dd-4c40-9249-4a9bdca375be)
   ![image](https://github.com/rtCamp/embed-google-drive/assets/56588503/77b84546-c5f8-4d3b-a613-ae37ed9d29f8)
   ![image](https://github.com/rtCamp/embed-google-drive/assets/56588503/57c5e5bb-7df2-469d-9e22-29a3e1655dc6)

## Video Guide
https://github.com/rtCamp/embed-google-drive/assets/56588503/d376c750-c0f8-4bfe-8b23-79ae1f070f46

**Comment by SH4LIN** [comment]
## Update

The plugin update required some additional tasks other than those mentioned before.
   - Go through the WordPress plugin release documentation and verify every step mentioned there. `~2hr`
   - Perform manual testing after every minor update. Plugin release `~1hr`

CC: @dhawalepranav

**Comment by nirajgiriXD** [comment]
## Tasks

Since the plugin has already been tested up to PHP 8.2 by @SH4LIN, I will proceed with testing it for WordPress 6.6. `~2hr`

cc: @vishal4669

**Comment by SH4LIN** [comment]
@nirajgiriXD Also, test the plugin upto PHP 8.3

**Comment by nirajgiriXD** [comment]
## Updates

- PHP 8.3 compatibility sweep completed. No issues were found
- WordPress 6.6 compatibility sweep completed. No issues were found

cc: @vishal4669, @SH4LIN

**Comment by nishitapandya** [comment]
Closed as completed
