### ISSUE TITLE
Text domain change from `rt-google-embeds` to `embed-google-drive`

### ISSUE THREAD

**Issue by SH4LIN** [rtCamp/embed-google-drive#20]
As per the WordPress plugin internationalization [Documentation](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/)

> If your plugin is hosted on wordpress.org it must be the slug portion of your plugin URL (wordpress.org/plugins/<slug>)

Our plugin slug is https://wordpress.org/plugins/embed-google-drive -> `embed-google-drive` but text domain is `rt-google-embeds`

A plan of action will be suggested by @vishalkakadiya 

Changing Domain:
- Change the text-domain as per the [wp.org](http://wp.org/) plugin’s slug.
- Replace the text domain in the plugin files.
- Generate a new .po file by running the npm run language command.
- Test the whole plugin’s functionality.
- Release the plugin with minor version update.

CC: @dhawalepranav @joelabreo227

**Comment by nishitapandya** [comment]
**1. File Renaming and Text Domain Updates (Estimated Time: 1.5 - 2 hours)**

**Tasks:**
- [ ] Update text domain in all PHP files
- [ ] Rename main plugin file from rt-google-embeds.php to embed-google-drive.php
- [ ] Update references to the old filename in all relevant files
- [ ] Update @package keywords in PHP files
- [ ] Update package.json
- [ ] Update composer.json
- [ ] Update .distignore and .gitignore
- [ ] Check and update any other files using rt-google-embeds

**2. Language File Updates (Estimated Time: 30 - 45 minutes)**

**Tasks:**
- [ ] Generate new language files after updating the text domain (npm run language)
- [ ] Update references of the old language file name with the new one

**3. Testing (Estimated Time: 3 - 4 hours)**

**Tasks:**
- [ ] Test all plugin functionality
- [ ] Verify translations are working
- [ ] Run automated tests
- [ ] Test compatibility with different WordPress versions
- [ ] Ensure all features work as expected

**4. Raising PR (Estimated Time: 10 - 15 minutes)**

**Tasks:**
- [ ] Open a pull request with all the changes

**5. Merging PR & Creating Release (Estimated Time: 30 - 45 minutes)**

**Tasks:**
- [ ] Update plugin version number
- [ ] Write and publish release notes
- [ ] Test the final release package

**Comment by Anuj-Rathore24** [comment]
---

**Additional updates made:**

* Renamed the class name and its corresponding file - [REF](https://github.com/rtCamp/embed-google-drive/tree/master/includes/classes)
* Renamed all constants in the plugin file along with their references - [REF](https://github.com/rtCamp/embed-google-drive/blob/d012e9f7cf9e7ec94887495feb0d828c693d7cfe/rt-google-embeds.php#L17)
* Updated the REST API namespace [REF](https://github.com/rtCamp/embed-google-drive/blob/d012e9f7cf9e7ec94887495feb0d828c693d7cfe/includes/classes/class-rtcamp-google-embeds.php#L258)
* Fixed a typo in the test files.

---
